### PR TITLE
feat: add notification on sync success or error

### PR DESCRIPTION
**Pull request by neroze**
General feature to show a desktop notification to the user on sync success or error

### CODE REVIEW

**Comment by Splurov** [comment]
Thanks for the contribution.
Please add configuration option to enable notifications.

**Comment by neroze** [comment]
> Thanks for the contribution.
> Please add configuration option to enable notifications.

updated

**Comment by Splurov** [comment]
Thanks, merged with some minor changes

**Comment by neroze** [comment]
> Thanks, merged with some minor changes

cheers

**Pull request merged**
